# Enter your code here
a="Python programming"
print(a.upper())
print(a.lower())
print(a.title())
print(a.strip())
print(a.lstrip())
print(a.rstrip())
print(a.replace('Python','java'))
print(a.find("Python"))
print(a.startswith("P"))
print(a.endswith("g"))
print(a.isalnum())
print(a.isdigit())
print(a.isalpha())